/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jaja_home_jni_JNI */

#ifndef _Included_com_jaja_home_jni_JNI
#define _Included_com_jaja_home_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jaja_home_jni_JNI
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jaja_home_jni_JNI_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
